"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


"""
def solve():
    P = [1]
    P.append(2)
    t = P[-1] + P[-2]
    while t <= 4000000:
        P.append(t)
        t = P[-1] + P[-2]
    ans = 0
    for v in P:
        if v & 1 ^ 1:
            ans += v
    return ans
if __name__ == '__main__':
    print(solve())
